name: Build and Deploy Codeigniter

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DCH_SMO_USER }}
          password: ${{ secrets.DCH_SMO_PASSWORD }}

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          tags: |
            docker.io/smartonedev/linasinvoice:latest
            docker.io/smartonedev/linasinvoice:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.OVH_SMO_SSH_HOST }}
          username: ${{ secrets.OVH_SMO_SSH_USER }}
          password: ${{ secrets.OVH_SMO_SSH_PASSWORD }}
          script: |
            cd /opt/apps/linasinvoice

            echo "> Pulling latest image"
            docker compose pull

            echo "> Updating services (zero downtime)"
            docker compose up -d

            echo "> Cleaning old images"
            docker image prune -f

            echo "> Deployment completed!"
